# Generated by Django 5.1.1 on 2024-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diemthi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd', models.CharField(max_length=10, unique=True)),
                ('toan', models.FloatField(null=True)),
                ('ngu_van', models.FloatField(null=True)),
                ('ngoai_ngu', models.FloatField(null=True)),
                ('vat_li', models.FloatField(null=True)),
                ('hoa_hoc', models.FloatField(null=True)),
                ('sinh_hoc', models.FloatField(null=True)),
                ('lich_su', models.FloatField(null=True)),
                ('dia_li', models.FloatField(null=True)),
                ('gdcd', models.FloatField(null=True)),
                ('ma_ngoai_ngu', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NaturalScienceStudent',
        ),
        migrations.DeleteModel(
            name='SocialScienceStudent',
        ),
    ]
